PROTOCOL_VERSION = 1
DEFAULT_HOST = "127.0.0.1"
DEFAULT_PORT = 9000
BUFFER_SIZE = 4096
HEADER_SIZE = 13
MAX_RETRIES = 5
RETRY_TIMEOUT_MS = 500
ACK_TIMEOUT_MS = 1000
HEARTBEAT_INTERVAL_MS = 5000
CONNECTION_TIMEOUT_MS = 30000
RECV_WINDOW_SIZE = 64
SEND_BUFFER_SIZE = 256
MAX_PACKET_SIZE = 1400

PACKET_TYPE = {
    "NONE": 0,
    "LOGIN": 1,
    "REGISTER": 2,
    "LOGOUT": 3,
    "GET_CHARACTER": 10,
    "SAVE_CHARACTER": 11,
    "CREATE_CHARACTER": 12,
    "LIST_CHARACTERS": 13,
    "SELECT_CHARACTER": 14,
    "DELETE_CHARACTER": 15,
    "POSITION_UPDATE": 20,
    "BATTLE_ACTION": 21,
    "CHAT_MESSAGE": 30,
    "HEARTBEAT": 50,
    "ACK": 51,
    "NACK": 52,
    "ERROR": 100,
}

RELIABLE_TYPES = frozenset(
    {
        PACKET_TYPE["LOGIN"],
        PACKET_TYPE["REGISTER"],
        PACKET_TYPE["LOGOUT"],
        PACKET_TYPE["GET_CHARACTER"],
        PACKET_TYPE["SAVE_CHARACTER"],
        PACKET_TYPE["CREATE_CHARACTER"],
        PACKET_TYPE["LIST_CHARACTERS"],
        PACKET_TYPE["SELECT_CHARACTER"],
        PACKET_TYPE["DELETE_CHARACTER"],
        PACKET_TYPE["BATTLE_ACTION"],
        PACKET_TYPE["CHAT_MESSAGE"],
    }
)
